defaults:
  - _self_
  - generate_cfg: top_k_top_p

_target_: src.model.cst.CST
image_encoder: resnet152
dim: 512
finetune_image_encoder: false
max_transformations: ${dataset.dataset_cfg.train.max_transformations}
num_lstm_layers: 1
lstm_dropout: 0.3
