_target_: src.criterion.tell.TTCriterion
loss:
  _target_: src.criterion.loss.TellingLossV1
  logit_shift: -1
  label_shift: -1
  text_model: "ViT-B/32"
  w_generate: 1.
  w_classify: 1.
  w_construct: 1.
  w_category: 1.
  w_topic: 1.
bert_score_model: "/data/pretrain/transformers/roberta-large"
category: true
topic: true
